# Generated by Django 5.1.3 on 2024-11-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0006_role_cart_customer_cartproduct_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='customer',
        ),
    ]
