# Generated by Django 5.1.3 on 2024-11-21 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0007_remove_cart_customer_remove_cartproduct_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groceryapp.role'),
            preserve_default=False,
        ),
    ]
